'use client'
import './globals.css'
import {Inter} from 'next/font/google'
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";
import {AuthProvider} from "../../contexts/AuthContext";

const inter = Inter({subsets: ['latin']})
const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            refetchOnWindowFocus: false,// default: true
            staleTime: 1000 * 60 * 60 * 24,
        },
    },
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <QueryClientProvider client={queryClient}>
            <AuthProvider>
                <html lang="en">
                <body className={inter.className}>{children}</body>
                </html>
            </AuthProvider>
        </QueryClientProvider>
    )
}
